Add controller Service Instance test
piotrmiskiewicz/service-catalog pull request #1
Opened 2019-04-16 07:54 UTC by jasiu001

Related to [#3113](https://github.com/kyma-project/kyma/issues/3113). Controller tests for ServiceInstance.

2019-04-16 11:26 UTC, piotrmiskiewicz reviewed
Create methods like AssertXXX(t *testing.T, ....) instead of Ensure

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +	require.NoError(t, ct.WaitForClusterServiceClass())
do we need to wait for the class? the same for plan

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +			require.NoError(t, ct.EnsureInstanceObservedGeneration(0))
does not make sense

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +			require.NoError(t, ct.CheckFeatureGate(state.enableFeatureGate))
Where do you set the feature gate?
the name CheckFeatureGate is saying - check the feature gate, but I'm looking deeper and there is a logic with dashboardURL - let's discuss structure the test

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/case_test.go
> +func (ct *controllerTest) EnsureBrokerActionExist(actionType fakeosb.ActionType) error {
there are methods like: NumberOfOSBProvisionCalls which can be used

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/case_test.go
> +func (ct *controllerTest) EnsureLastUpdateBrokerActionHasCorrectPlan(planID string) error {
create a method which returns last update planID or create a method something like AssertLastOSBUpdatePlanID

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +			require.NoError(t, ct.EnsureBrokerActionExist(fakeosb.UpdateInstance))
change ensure to NumberOf...

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +				require.NoError(t, ct.EnsureBrokerActionNotExist(fakeosb.DeprovisionInstance))
require.Zero(t, ct.NumberOfOSBDeprovisionCalls())

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +				require.NoError(t, ct.EnsureServiceInstanceHasCondition(condition))
use WaitForInstanceCondition

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +	require.NoError(t, ct.CreateServiceBrokerWithIncreaseRelistRequests())
ct.CreateSimpleClusterServiceBroker(),

why do you need increasing relist requests

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +			require.NoError(t, ct.EnsureBrokerActionExist(fakeosb.UpdateInstance))
ct.NumberOfUpdateCalls (you need to create such method, see other NumberOf... methods)

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +			require.NoError(t, ct.EnsureBrokerActionWithParametersExist(state.expectedParams))
ct.AssertLastUpdateAction, see AssertLastBindRequest

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +				require.NoError(t, ct.EnsureServiceInstanceOrphanMitigationStatus(true))
AssertServiceinstanceOrphanMitigationStatus

2019-04-16 11:26 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +			require.NoError(t, ct.EnsureBrokerActionExist(fakeosb.ProvisionInstance))
use ct.NumberOfProvisionCalls

2019-04-16 13:33 UTC, jasiu001 commented on pkg/controller/controller_flow_instance_test.go
> +	require.NoError(t, ct.WaitForClusterServiceClass())
The original test waits for [class](https://github.com/kubernetes-incubator/service-catalog/blob/master/test/integration/controller_instance_test.go#L188) and [plans](https://github.com/kubernetes-incubator/service-catalog/blob/master/test/integration/controller_instance_test.go#L209). In my opinion they wanted to be sure provision failed due lack of ServiceBroker not class or plans. Should it be omitted? I am not sure

2019-04-18 05:44 UTC, piotrmiskiewicz requested changes

2019-04-18 05:44 UTC, piotrmiskiewicz commented on pkg/controller/case_test.go
> +func (ct *controllerTest) AssertBrokerActionWithParametersExist(parameters map[string]interface{}) error {
it asserts update action - fix the name

2019-04-18 05:44 UTC, piotrmiskiewicz commented on pkg/controller/case_test.go
> +func (ct *controllerTest) AssertLastOSBUpdatePlanID() error {
please, refactor all Assert* methods to have one argument t *testing.T, see existing AssertOSBBasicAuth

2019-04-18 05:44 UTC, piotrmiskiewicz commented on pkg/controller/controller_flow_instance_test.go
> +			}
try such test:
```
t.Run(tn, func(t *testing.T) {
			// GIVEN
			ct := newControllerTest(t)
			defer ct.TearDown()

			//if state.enableFeatureGate {
			oldValue := utilfeature.DefaultFeatureGate.Enabled(scfeatures.UpdateDashboardURL)
			utilfeature.DefaultFeatureGate.Set(fmt.Sprintf("%v=%v", scfeatures.UpdateDashboardURL, state.enableFeatureGate))
			defer utilfeature.DefaultFeatureGate.Set(fmt.Sprintf("%v=%v", scfeatures.UpdateDashboardURL, oldValue))
			//}

			require.NoError(t, ct.CreateSimpleClusterServiceBroker())
			require.NoError(t, ct.WaitForReadyBroker())

			// WHEN
			require.NoError(t, ct.CreateServiceInstance())


			// THEN
			require.NoError(t, ct.WaitForReadyInstance())

			ct.SetUpdateServiceInstanceResponseWithDashboardURL()

			ct.UpdateServiceInstanceParameters()

			time.Sleep(time.Second)

			if state.enableFeatureGate {
				require.NoError(t, ct.AssertServiceInstanceDashboardURL())
			} else {
				require.NoError(t, ct.AssertServiceInstanceEmptyDashboardURL())
			}
		})
```

2019-06-12 08:34 UTC, closed without merging

2019-06-25 10:44 UTC, jasiu001 commented
PR moved to main fork [#2667](https://github.com/kubernetes-sigs/service-catalog/pull/2667)